In [1]:
import torch
import pandas as pd
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from torch.utils.data import TensorDataset, DataLoader

In [2]:
column_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
data = pd.read_csv("housing.csv", header = None, delimiter = r"\s+", names = column_names)

In [3]:
data.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    int64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(12), int64(2)
memory usage: 55.5 KB

In [5]:
scaler = preprocessing.MinMaxScaler()
names = data.columns
d = scaler.fit_transform(data)
df = pd.DataFrame(d, columns=names)
df.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.000000,0.18,0.067815,0.0,0.314815,0.577505,0.641607,0.269203,0.000000,0.208015,0.287234,1.000000,0.089680,0.422222
1,0.000236,0.00,0.242302,0.0,0.172840,0.547998,0.782698,0.348962,0.043478,0.104962,0.553191,1.000000,0.204470,0.368889
2,0.000236,0.00,0.242302,0.0,0.172840,0.694386,0.599382,0.348962,0.043478,0.104962,0.553191,0.989737,0.063466,0.660000
3,0.000293,0.00,0.063050,0.0,0.150206,0.658555,0.441813,0.448545,0.086957,0.066794,0.648936,0.994276,0.033389,0.631111
4,0.000705,0.00,0.063050,0.0,0.150206,0.687105,0.528321,0.448545,0.086957,0.066794,0.648936,1.000000,0.099338,0.693333

In [6]:
features = df.drop('MEDV', axis=1).to_numpy()
target = df.MEDV.to_numpy()

In [7]:
features = torch.tensor(features, dtype = torch.float32)
target = torch.tensor(target, dtype = torch.float32)
#X = X.clone().detach().requires_grad_(True)

In [9]:
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

In [8]:
batch_size = 10
dataset = TensorDataset(features, target)
# Randomly reading mini-batches
data_iter = DataLoader(dataset, batch_size, shuffle=True)

# Read a batch to see how it works
for X, y in data_iter:
    print(X, y)
    break

tensor([[1.9900e-03, 0.0000e+00, 1.0000e+00, 0.0000e+00, 4.6091e-01, 3.5505e-01,
         9.8249e-01, 5.6907e-02, 1.3043e-01, 1.0000e+00, 7.9787e-01, 8.6674e-01,
         6.1369e-01],
        [2.0854e-03, 0.0000e+00, 2.5367e-01, 0.0000e+00, 2.2222e-01, 5.4991e-01,
         1.2152e-01, 3.8977e-01, 1.7391e-01, 1.9084e-01, 7.4468e-01, 9.9188e-01,
         9.2439e-02],
        [1.2105e-04, 9.0000e-01, 5.7185e-02, 0.0000e+00, 5.1440e-02, 6.0682e-01,
         3.4192e-01, 1.0000e+00, 1.7391e-01, 0.0000e+00, 4.6809e-01, 9.6863e-01,
         7.6435e-02],
        [5.4682e-02, 0.0000e+00, 6.4663e-01, 0.0000e+00, 4.7119e-01, 5.6007e-01,
         9.3409e-01, 1.0691e-01, 1.0000e+00, 9.1412e-01, 8.0851e-01, 9.9826e-01,
         4.6772e-01],
        [5.7752e-03, 2.0000e-01, 1.2867e-01, 0.0000e+00, 5.3909e-01, 9.2681e-01,
         9.1246e-01, 1.0538e-01, 1.7391e-01, 1.4695e-01, 4.2553e-02, 9.7468e-01,
         1.1534e-01],
        [3.2805e-03, 0.0000e+00, 2.1041e-01, 0.0000e+00, 2.4486e-01, 7.9038e-01,
         1.4521e-01, 2.0419e-01, 3.0435e-01, 2.2901e-01, 5.1064e-01, 9.5111e-01,
         6.0430e-02],
        [3.4540e-04, 2.0000e-01, 1.0521e-01, 0.0000e+00, 1.1914e-01, 6.5281e-01,
         3.5324e-01, 3.7421e-01, 1.7391e-01, 5.5344e-02, 2.4468e-01, 9.8822e-01,
         7.8918e-02],
        [9.9809e-04, 0.0000e+00, 4.5345e-01, 0.0000e+00, 1.0700e-01, 5.2213e-01,
         4.3357e-01, 3.0672e-01, 1.7391e-01, 4.0267e-01, 6.4894e-01, 9.6553e-01,
         1.9895e-01],
        [1.3500e-02, 0.0000e+00, 7.0088e-01, 0.0000e+00, 4.5267e-01, 4.4338e-01,
         9.4439e-01, 1.1788e-01, 1.7391e-01, 4.1221e-01, 2.2340e-01, 7.3622e-01,
         3.5044e-01],
        [1.8889e-01, 0.0000e+00, 6.4663e-01, 0.0000e+00, 6.4815e-01, 3.2880e-01,
         9.8043e-01, 2.6962e-02, 1.0000e+00, 9.1412e-01, 8.0851e-01, 1.0000e+00,
         8.0243e-01]]) tensor([0.0444, 0.4356, 0.5578, 0.2600, 0.9733, 0.9267, 0.6756, 0.3644, 0.2756,
        0.0489])

In [9]:
model = torch.nn.Sequential(torch.nn.Linear(13, 1))

In [10]:
loss = torch.nn.MSELoss(reduction='mean')

In [11]:
#trainer = torch.optim.SGD(model.parameters(), lr=0.001)

In [13]:
trainer = torch.optim.Adam(model.parameters(), lr=0.001)

In [14]:
num_epochs = 1000
for epoch in range(1, num_epochs + 1):
    for X, y in data_iter:
        trainer.zero_grad()
        l = loss(model.forward(X).reshape(-1), y)
        l.backward()
        trainer.step()
    l = loss(model.forward(features).reshape(-1), target)
    if epoch % 100 == 0:
        print('epoch %d, loss %f' % (epoch, l.item()))
        print('w',model[0].weight.data)
        print('b',model[0].bias.data)

epoch 100, loss 0.011502
w tensor([[-0.1510,  0.0926, -0.0052,  0.0665, -0.0915,  0.5846,  0.0184, -0.2349,
          0.0821, -0.0674, -0.1419,  0.1471, -0.3745]])
b tensor([0.2277])
epoch 200, loss 0.010917
w tensor([[-0.1972,  0.0989,  0.0148,  0.0584, -0.1621,  0.5217,  0.0034, -0.3148,
          0.1342, -0.1238, -0.1789,  0.1056, -0.3848]])
b tensor([0.3694])
epoch 300, loss 0.010837
w tensor([[-0.2056,  0.1007,  0.0164,  0.0586, -0.1790,  0.4787,  0.0026, -0.3424,
          0.1498, -0.1379, -0.1908,  0.0925, -0.4047]])
b tensor([0.4314])
epoch 400, loss 0.010840
w tensor([[-0.2107,  0.1051,  0.0143,  0.0580, -0.1856,  0.4588,  0.0018, -0.3481,
          0.1532, -0.1419, -0.1959,  0.0876, -0.4133]])
b tensor([0.4605])
epoch 500, loss 0.010836
w tensor([[-0.2138,  0.1025,  0.0155,  0.0618, -0.1883,  0.4479,  0.0035, -0.3578,
          0.1570, -0.1415, -0.1968,  0.0839, -0.4204]])
b tensor([0.4721])
epoch 600, loss 0.011255
w tensor([[-0.2173,  0.1003,  0.0100,  0.0600, -0.1939,  0.4414, -0.0021, -0.3611,
          0.1522, -0.1466, -0.2020,  0.0789, -0.4234]])
b tensor([0.4724])
epoch 700, loss 0.010922
w tensor([[-0.2136,  0.1029,  0.0146,  0.0583, -0.1896,  0.4445,  0.0043, -0.3582,
          0.1566, -0.1423, -0.1964,  0.0840, -0.4205]])
b tensor([0.4808])
epoch 800, loss 0.010815
w tensor([[-0.2131,  0.1050,  0.0108,  0.0592, -0.1924,  0.4407,  0.0009, -0.3597,
          0.1558, -0.1440, -0.1990,  0.0832, -0.4222]])
b tensor([0.4803])
epoch 900, loss 0.011024
w tensor([[-0.2095,  0.1056,  0.0161,  0.0621, -0.1904,  0.4436,  0.0034, -0.3604,
          0.1592, -0.1404, -0.1973,  0.0839, -0.4187]])
b tensor([0.4835])
epoch 1000, loss 0.010842
w tensor([[-0.2122,  0.1033,  0.0120,  0.0592, -0.1924,  0.4402,  0.0010, -0.3613,
          0.1560, -0.1439, -0.2008,  0.0806, -0.4238]])
b tensor([0.4798])